'use client';

import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { Providers } from './providers';
import { Toaster } from 'react-hot-toast';
import { useThemeStore } from '@/store/themeStore';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isDarkMode } = useThemeStore();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted) {
      if (isDarkMode) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    }
  }, [isDarkMode, mounted]);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" sizes='16x16' />
      </head>
      <body className={`${inter.className} antialiased`}>
        <Providers>
          {children}
          <Toaster 
            position="top-right"
            toastOptions={{
              className: 'dark:bg-dark-paper dark:text-dark-text',
            }}
          />
        </Providers>
      </body>
    </html>
  );
} 